name: continuous-integration

on:
  push:
    branches: [fix-workflow]
  #   tags:
  #     - 'v*'
  # pull_request:

jobs:
  docs:
    name: Documentation build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[rtd]
      - name: Build docs
        run: |
          cd docs
          make clean
          make html
